### ISSUE TITLE
Question about tiers

### ISSUE THREAD

**Issue by acok06** [WanderingEye0/The-Gatherer#15]
Hello,

I used your project to test out and it works with you example datas for T1 stone. For example I want to collect Tier3-4 stone, do I need to train it again or it will catch the similary and gather resources ?

**Comment by acok06** [comment]
Okay I found that that when we add some dataset to the models, it works fine. But I have additional question, how can I work this in two vm's ?

**Comment by Riczap** [comment]
Hi, you should train a new model for the specific resources that you want to farm. 

And I'm not very sure on how you could run the bot on multiple instances since it's using pyautogui to simulate the mouse clicks. Unless you could create two VMs that have individual cursors, I think you won't be able to do it. Sorry!

**Comment by Riczap** [comment]
I found this post that might be helpful.
https://www.reddit.com/r/virtualbox/s/Cq8u8eDRDw

**Comment by acok06** [comment]
thank you I found the solution with using two mouses. There is an option in VMware Workstation for selecting which mouse should use in VM.
